version: '3'
networks:
  pulsar-network:
    # Write the name of your pulsar-network here
    name: 
    external: true

services:
  prometheus:
    image: pulsarportrait/prometheus:latest
    container_name: prometheus
    networks:
      - pulsar-network
    ports:
      - '9090:9090'
    volumes:
      - ./imageConfigs/prometheus/promData:/prometheus

  grafana:
    image: pulsarportrait/grafana:latest
    container_name: grafana
    networks:
      - pulsar-network
    ports:
      - "2222:3000"
    depends_on:
      - prometheus

  pulsarportrait:
    image: pulsarportrait/app:latest
    container_name: pulsarportrait
    networks:
      - pulsar-network
    ports:
      - '3333:3333'