global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pulsar'
    scrape_interval: 5s
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['host.docker.internal:8080']
      # - targets: ['broker:8080']